global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'calendar-app'
    static_configs:
      - targets: ['calendar-app:8080']
    metrics_path: '/metrics'

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']