server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 1s
      max_period: 5s
      max_retries: 5

scrape_configs:
  - job_name: calendar
    static_configs:
      - targets: [localhost]
        labels:
          job: calendar-logs
          __path__: /var/log/calendar/*.log